# Generated by Django 3.1.4 on 2021-10-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20211001_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dateOfPayemnt',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
