# Generated by Django 3.1.4 on 2021-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_dateofpayemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dateOfPayemnt',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
