# Generated by Django 3.1.4 on 2021-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20211001_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dateOfPayemnt',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
