# Generated by Django 3.1.4 on 2021-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20211001_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='dateOfPayemnt',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_time',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
