# Generated by Django 3.1.4 on 2021-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20211001_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dateOfPayment',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_time',
            field=models.DateTimeField(null=True),
        ),
    ]
