# Generated by Django 3.0.7 on 2021-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expense_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
